<?php

require "../db/config.php";
require "../assets/regression/polynomial/PolynomialRegression.php";

//Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//Call login API to get security token
//curl https://dev.bondlinc.com/bondWeb/Api/login -d '{"lang":"en-US","uid":"eric","pass":"1111"}'
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://dev.bondlinc.com/bondWeb/Api/login");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"lang\":\"en-US\",\"uid\":\"".$uid."\",\"pass\":\"".$pass."\"}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

$decoded = json_decode($result);

$token = $decoded->data->auth_token;

//Get bond search parameters from POST
$moody_st = $_POST['moody_st'];
$moody_ed = $_POST['moody_ed'];
$sp_st = $_POST['sp_st'];
$sp_ed = $_POST['sp_ed'];
$fitch_st = $_POST['fitch_st'];
$fitch_ed = $_POST['fitch_ed'];
$yield_st = ((float)$_POST['yield_Low'])*100;
$yield_ed = ((float)$_POST['yield_High'])*100;
$maturity_st = $_POST['tenor_Low'];
$maturity_ed = $_POST['tenor_High'];
//A cap on the number of results queried. Could toggle lower for efficient testing.
$max_results = "100000";
$currency = $_POST['currencyPHP'];
$region = $_POST['regionPHP'];
$unrated = $_POST['unrated'];

$query = "";
customizeQuery();
bondscreener();


function customizeQuery()
{
    if ($GLOBALS['currency'] == "Unspecified")
    {
        $GLOBALS['currency'] = "";
    }

    if ($GLOBALS['region'] == "Unspecified")
    {
        $GLOBALS['region'] = "";
    }

    if ($GLOBALS['unrated'] == "Yes")
    {
        //If the user wants to search for unrated bonds, then delete the rating search criteria.
        
        $GLOBALS['moody_st'] = "";
        $GLOBALS['moody_ed'] = "";
        $GLOBALS['sp_st'] = "";
        $GLOBALS['sp_ed'] = "";
        $GLOBALS['fitch_st'] = "";
        $GLOBALS['fitch_ed'] = "";
        
    }

    $GLOBALS['query'] = "{\"lang\":\"en-US\",\"auth_token\":\"".$GLOBALS['token']."\",\"start\":1,\"rows\":".$GLOBALS['max_results'].",\"sector\":\"\",\"mtytype\":\"\",\"ring\":\"\",\"country\":\"\",\"currency\":\"".$GLOBALS['currency']."\",\"moody_st\":\"".$GLOBALS['moody_st']."\",\"moody_ed\":\"".$GLOBALS['moody_ed']."\",\"sp_st\":\"".$GLOBALS['sp_st']."\",\"sp_ed\":\"".$GLOBALS['sp_ed']."\",\"fitch_st\":\"".$GLOBALS['fitch_st']."\",\"fitch_ed\":\"".$GLOBALS['fitch_ed']."\",\"yield_st\":".$GLOBALS['yield_st'].",\"yield_ed\":".$GLOBALS['yield_ed'].",\"maturity_st\":".$GLOBALS['maturity_st'].",\"maturity_ed\":".$GLOBALS['maturity_ed']."}";
    
}

function bondscreener()
{
    //API call for bondscreener
    $ch2 = curl_init();

    curl_setopt($ch2, CURLOPT_URL, "https://dev.bondlinc.com/bondWeb/Api/bond/bondScreenerList");
    curl_setopt($ch2, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch2, CURLOPT_POSTFIELDS, $GLOBALS['query']);
    curl_setopt($ch2, CURLOPT_POST, 1);

    $headers2 = array();
    $headers2[] = "Content-Type: application/x-www-form-urlencoded";
    curl_setopt($ch2, CURLOPT_HTTPHEADER, $headers2);

    $result2 = curl_exec($ch2);
    if (curl_errno($ch2)) {
        echo 'Error:' . curl_error($ch2);
    }
    curl_close ($ch2);

    $phpResponse = json_decode($result2);

    runRegression($result2);
}

function runRegression($bondSearchResult)
{
    //Getting all bonds to run regression
    $ch3 = curl_init();

    curl_setopt($ch3, CURLOPT_URL, "https://dev.bondlinc.com/bondWeb/Api/bond/bondScreenerList");
    curl_setopt($ch3, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch3, CURLOPT_POSTFIELDS, "{\"lang\":\"en-US\",\"auth_token\":\"".$GLOBALS['token']."\",\"start\":1,\"rows\":".$GLOBALS['max_results'].",\"sector\":\"\",\"mtytype\":\"\",\"ring\":\"\",\"country\":\"\",\"currency\":\"".$GLOBALS['currency']."\",\"moody_st\":\"".""."\",\"moody_ed\":\"".""."\",\"sp_st\":\"".""."\",\"sp_ed\":\"".""."\",\"fitch_st\":\"".""."\",\"fitch_ed\":\"".""."\",\"yield_st\":"."0".",\"yield_ed\":"."130".",\"maturity_st\":"."0.1".",\"maturity_ed\":"."130"."}");
    curl_setopt($ch3, CURLOPT_POST, 1);

    $headers3 = array();
    $headers3[] = "Content-Type: application/x-www-form-urlencoded";
    curl_setopt($ch3, CURLOPT_HTTPHEADER, $headers3);

    $result3 = curl_exec($ch3);
    if (curl_errno($ch3)) {
        echo 'Error:' . curl_error($ch3);
    }
    curl_close ($ch3);

    $regressionData = array();              //array to store yield and tenor used for regression calculation
    $phpResponse = json_decode($result3);
    $bondArray = $phpResponse->data->list;

    for($i = 0; $i < count($bondArray); $i++)
    {
        array_push($regressionData, array(log((float)$bondArray[$i]->matYear), ((float)($bondArray[$i]->yield))/100));
        //The matYear represents time to the final maturity, not the call date!! This might be a problem as in previous versions,
        //we took the time to the shorter of the final maturity and the next call as the tenor.
    }

    //Starting regression calculation.
    //Precision digits in BC math. 
    bcscale( 10 ); 

    // Start a regression class 
    $regression = new PolynomialRegression( 2 ); 

    // Add all the data to the regression analysis. 
    foreach ( $regressionData as $dataPoint ) {
        $regression->addData( $dataPoint[ 0 ], $dataPoint[ 1 ] ); 
    }

    // Get coefficients for the polynomial. 
    $coefficients = $regression->getCoefficients(); 

    $slope = $coefficients[ 1 ];
    $y = $coefficients[ 0 ];

    returnResults($bondSearchResult, $slope, $y);
}

function returnResults($bondSearchResult, $slope, $y)
{
    $returnedItem = array($bondSearchResult, $slope, $y, $GLOBALS['query']);
    
    $encoded = json_encode($returnedItem);
    echo $encoded;
}

function autocomplete()
{
    //API call for autocomplete
    $ch2 = curl_init();

    curl_setopt($ch2, CURLOPT_URL, "https://dev.bondlinc.com/bondWeb/Api/search/autocomplete");
    curl_setopt($ch2, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch2, CURLOPT_POSTFIELDS, "{\"lang\":\"en-US\",\"auth_token\":\"".$GLOBALS['token']."\",\"securityname\":\"SWIRE\",\"sortColumn\":\"maturity\",\"orderBy\":0,\"start\":1,\"rows\":500}");
    curl_setopt($ch2, CURLOPT_POST, 1);
    
    $headers2 = array();
    $headers2[] = "Content-Type: application/x-www-form-urlencoded";
    curl_setopt($ch2, CURLOPT_HTTPHEADER, $headers2);
    
    $result2 = curl_exec($ch2);
    if (curl_errno($ch2)) {
        echo 'Error:' . curl_error($ch2);
    }
    curl_close ($ch2);
    
    echo $result2;
}

?>